---
title: "stratification factors for OS analysis"
author: "wei zou"
date: "`r Sys.time()`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F)

source('~/R/lib_2020/ae_helper.r')
library(knitr)
library(Biobase)
library(survival)
 
load('~/2OBD/PDL1mab/go29436_impower150/ngs/intermdata/clinical_3rd_os/impower150_3rd_os_3.1.Rdata')


ds1 <- eset2vad(es2b)

```
 

# arm   C prognostic effects 

```{r, echo=T}
ds3 <- subset(ds1, ARMCD1 %in% c('C','A') & ITTWTFL %in%  'Y')
ds3$ARMCD1 <- factor(ds3$ARMCD1, levels=c('C','A' ))
survfit( Surv(OS, OS.event) ~ ARMCD1, data=ds3) 

ds3$strata_sex <- factor(ds3$strata_sex, levels=c('M','F'))



c_sex <- coxph( Surv(OS, OS.event) ~ strata_sex  , data =   subset(ds3, as.character( ARMCD1 ) %in% 'C' ) )

print(c_sex)

ds3$strata_liver <- factor(ds3$strata_liver, levels=c("PRESENT" ,"NOT PRESENT"))

c_liver <- coxph( Surv(OS, OS.event) ~ strata_liver  , data =   subset(ds3, as.character( ARMCD1 ) %in% 'C' ) )

print(c_liver)



coxph( Surv(OS, OS.event) ~ strata_IHC  , data =   subset(ds3, as.character( ARMCD1 ) %in% 'C' ) )

ds3$strata_IHC <- factor(ifelse(ds3$strata_IHC %in% 'TC0/1/2_IC0/1','PDL-','PDL+'), levels=c('PDL-','PDL+'))

c_ihc <- coxph( Surv(OS, OS.event) ~ strata_IHC  , data =   subset(ds3, as.character( ARMCD1 ) %in% 'C' ) )

print(c_ihc)

```

analysis data has `r nrow(ds3)` patients. Duration of follow up is `r round( as.integer( as.Date( unique(ds3$DCUTDT) ) - min(as.Date(ds3$RANDDT))) / (365.25/12),1) ` month


```{r, echo =F}

vars <- c('strata_sex','strata_liver','strata_IHC')

feature.table <- data.frame(var=vars, 
              referLevel = sapply(vars, function(v) levels(ds3[[v]])[1]),
              targetLevel = sapply(vars, function(v) levels(ds3[[v]])[2]),
              freq = sapply( vars, function(v) {
                r1 <- levels(ds3[[v]])[2]
                mean(ds3[[v]] == r1)
              }),
              hr = exp( c(c_sex$coefficients, c_liver$coefficients, c_ihc$coefficients) ), stringsAsFactors = F)
 
kable(feature.table, row.names = F, digits=2, caption ='stratification factors')


count1 <- with(ds3,   as.data.frame(table( strata_sex,strata_liver,strata_IHC)))

colnames(count1) <- gsub('Freq','n', colnames(count1))
count1$freq_obs <- count1$n/sum(count1$n)
count1$freq_multiply <- apply(count1[, 1:3],1, function(v) {
  mean( ds3[, 'strata_sex'] == v[1] ) * 
    mean(ds3[, 'strata_liver'] == v[2]) *
    mean(ds3[, 'strata_IHC'] == v[3])
  })

```

```{r, echo =F}

constructMedians <- function( bigN = 1e6, overallMed = 5, freq=c(M1=0.45, M2=0.2), hr = c(0.7, 0.4), check_medians =F) {
  # this function tries to construct subgroup hazard so that the hr 

f1 <- as.matrix( expand.grid(lapply(freq, function(x) c(x, 1-x))) ) # subgroup frequencies
f1.name <- NULL
if(!is.null(names(freq))) {
  f1.name <-   expand.grid(lapply(names(freq), function(x) c(paste(x,'+', sep=''), paste(x,'-', sep=''))), stringsAsFactors = F  )   # subgroup frequencies
  colnames(f1.name) <- names(freq)
   
}  
f2 <- exp( rowSums(log(f1)) )
stopifnot(abs( sum(f2)  - 1) < 1e-5)
c1 <- as.matrix( expand.grid(lapply(freq, function(x) c(x, x-1))) ) # coefficients
r1 <- log(2)/ overallMed * exp( c1 %*% matrix(log(hr), ncol =1) ) # rate of exponential distribution

stopifnot(length(f2) == length(r1))

s1 <- lapply(1:length(f2), function(i)  rexp(round(bigN * f2[i], 0), rate=r1[i]))

#names(s1) <- apply(f1, 1, paste, collapse=',')


r2 <- as.vector( r1 * median(unlist(s1)) / overallMed)



s1 <- lapply(1:length(f2), function(i)  rexp(round(bigN * f2[i], 0), rate=r2[i]))

if(!is.null(f1.name)) {
  
  f1.name$rate <- r2
  f1.name$sim_med <- sapply(s1, median)
  names(r2) <- names(f2) <- apply(f1.name[,names(freq)], 1, paste, collapse='')
  
  
  if(check_medians) {
    
    plot(density(unlist(s1)), col='black', main='overall distribution from simulation')
lines(density(rexp(10000, rate=log(2)/overallMed)), col='red')
legend('topright', lty=1, legend = c('mixed sim','standard exp'), col=c('black','red'))
    
    for( marker in names(freq)){
      print(marker)
      # individual groups: not done
       for ( j in grep(paste(marker,'+', sep=''), as.character(f1.name[[marker]]), fixed = T )) {
         
         cond1 <- paste(f1.name[j, setdiff(names(freq), marker  ),drop=T], collapse = ',')
         print(paste('conditional on', cond1))
         k <- which( apply(f1.name[ , setdiff(names(freq), marker  ),drop=F], 1, paste, collapse = ',') == cond1)
         temp <- sapply(k, function(k1) {if(k1 != j) print(f1.name[j,'rate'] / f1.name[k1,'rate'])})
       }
      
      # collapse other groups
      print(paste( 'marginal hr',
      
      median(do.call(c, s1[which(f1.name[[marker]] %in% paste(marker,'-',sep=''))])) / 
      median(do.call(c, s1[which(f1.name[[marker]] %in% paste(marker,'+',sep=''))]))  
      ) )
    }
  }
}  

 


invisible(  list(overallM = median(unlist(s1)), rate=r2, freq= f2) )
}


 

cm <- constructMedians( bigN = 1e6, overallMed = 14.7, freq=c(M1=0.375, M2=0.84, M3=0.25), hr = c(0.82, 0.7, 0.7), check_medians =T)


kable(count1, digits=3)


stopifnot( all( abs(sort(count1$freq_multiply)  - sort(cm$freq)) < 1e-2 ))

kable(data.frame( cm$rate, cm$freq), digits = 3, caption ='simulation input')
save(cm, file  = '~/projects/stratification/strat_simulation_input.rdata', version = 2)      

```

__freq_multiply__ is obtained by multiplying marginal frequency, i.e., assumming independence.


# reanalyze outcome with collapsed PDL1 subgroup

```{r, echo=F}

# modify the original print.survdiff to output statistics
summary.survdiff <- function(x, digits = max(options()$digits - 4, 3), ...) {

    saveopt <-options(digits=digits)
    on.exit(options(saveopt))

    if (!inherits(x, 'survdiff'))
	stop("Object is not the result of survdiff")
    if (!is.null(cl<- x$call)) {
	# cat("Call:\n")
	# dput(cl)
	# cat("\n")
	}

    omit <- x$na.action
    if (length(omit)) cat("n=", sum(x$n), ", ", naprint(omit),
					  ".\n\n", sep='')

    if (length(x$n)==1)  {
	z <- sign(x$exp - x$obs) * sqrt(x$chisq)
	temp <- c(x$obs, x$exp, z, signif(pchisq(x$chisq, 1, lower.tail=FALSE),
                                          digits))
	names(temp) <- c("Observed", "Expected", "Z", "p")
	print(temp)
	}
    else {
	if (is.matrix(x$obs)){
	    otmp <- apply(x$obs,1,sum)
	    etmp <- apply(x$exp,1,sum)
	    }
	else {
	    otmp <- x$obs
	    etmp <- x$exp
	    }
	df <- (sum(1*(etmp>0))) -1
	temp <- cbind(x$n, otmp, etmp, ((otmp-etmp)^2)/ etmp,
					 ((otmp-etmp)^2)/ diag(x$var), diag(x$var))
	dimnames(temp) <- list(names(x$n), c("N", "Observed", "Expected",
				  "(O-E)^2/E", "(O-E)^2/V",'V'))
	return(temp)
# 	cat("\n Chisq=", format(round(x$chisq,1)),
# 		 " on", df, "degrees of freedom, p=",
# 		 format.pval(pchisq(x$chisq, df, lower.tail=FALSE)),
#             "\n")
       }
#     invisible(x)
}


t1 <- with(ds3, table(paste(strata_sex,strata_liver,strata_IHC), ARMCD1))

t2 <- with(subset(ds3, OS.event==1), table(paste(strata_sex,strata_liver,strata_IHC), ARMCD1))

stopifnot(all(row.names(t1) == row.names(t2)))


t12 <- merge( unclass(t1),  unclass(t2), by=0, suffixes =c('_n','_event'))



s2 <- lapply( split(ds3, with(ds3, paste(strata_sex,strata_liver,strata_IHC))), function(d)   summary( survdiff( Surv(OS, OS.event) ~ ARMCD1   , data =   d) ))

s2_hr <- lapply( split(ds3, with(ds3, paste(strata_sex,strata_liver,strata_IHC))), function(d)   coxph( Surv(OS, OS.event) ~ ARMCD1   , data =   d)$coefficients ) 


stopifnot(all(names(s2) == names(s2_hr)))

t12$`O-E` <- sapply(t12[, 1], function(s)   s2[[s]]['ARMCD1=C','Observed'] - s2[[s]]['ARMCD1=C','Expected'] )
t12$`V` <-   sapply(t12[, 1], function(s)  s2[[s]]['ARMCD1=C', 'V'] )

t12$log_hr <- ifelse( abs(unlist(s2_hr)) < 10,  unlist(s2_hr), NA)
 


t12$prob_C_better <- pnorm(t12$log_hr, mean= log(0.8), sd=sqrt(1/t12[, 'C_event']+ 1/t12[,'A_event']), lower.tail = F)
kable(t12, row.names =F, digits=3)


```



