---
title: "simulation to study strategies to handle small strata"
author: "Wei Zou"
date: "`r Sys.time()`"
output: pdf_document
---


this program compare stratified vs unstratified analyses


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F)
library(knitr)
library(reshape2)
library(ggplot2)
spec <- list(home  = '~/projects/stratification' )

 source('~/R/lib_2020/data_functions.r')
source('~/R/lib_2020/output_functions.r')


summarizeMatrix2 <- function(ds3, vars=colnames(ds3)) {
    stopifnot(is.matrix(ds3) || is.data.frame(ds3))
    stopifnot(all(vars %in% colnames(ds3)))
     
    do.call(rbind, lapply(vars, function(i) {
        data.frame(var = i, 
                   n=sum(!is.na(ds3[, i])), 
                   mean=mean(ds3[, i], na.rm=T), sd=sd(ds3[, i], na.rm=T), 
                   matrix( quantile(ds3[, i], probs = c(0.01, 0.05, 0.1, 0.25, 0.5), na.rm=T, type=2 ), nrow=1, dimnames=list('', c('1%', '5%','10%','25%','50%') )), check.names = F)}
                          ))
}
source(paste(spec$home,'strat_functions.r', sep = '/'))
```

```{r parameters, echo=F}


load('~/projects/stratification/imvigor011_strat_freq.Rdata') 

t1$marker <- apply(t1[, row.names(feature.table)], 1, function(x) {
   paste( sapply(1:length(x), function(i) {
     s <- names(x)[i]
     if(x[s] == feature.table[s,'targetLevel']) return(paste('M', i,'+', sep =''))
     if(x[s] == feature.table[s,'referLevel'])  return(paste('M', i,'-', sep =''))
     return(NA)
  }),collapse = '') 
})

# decide parameters

cm <- constructMedians( bigN = 1e6, overallMed = 4.4, freq=c(M1=0.39, M2=0.26, M3=0.34, M4=0.22), hr = exp(c(-0.3, -0.8, -0.2, -0.35)), check_medians =T)

cm1 <- data.frame( cm$rate, cm$freq)

cm2 <- merge(cm1, t1,  by.x=0, by.y='marker')
colnames(cm2) <- gsub('Row.names','stratum',colnames(cm2))
cm2$med <- log(2) /  cm2$cm.rate
cm2$n <- 3 * round( cm2$freq * 240 /3)
cm2$n[cm2$n == 0] <- 3
cm2$hr <- 0.65
with(cm2, plot(x = cm.freq, y = freq, xlab= 'freq assuming indepence', ylab = 'observed joint freq'))
abline(0,1)

knitr::kable(cm2[, c('stratum', paste('STRAT', 1:4, sep =''), 'freq', 'n', 'med')], digits = 3, caption ='simulation input')

 
 



save(cm2,   feature.table, file= paste(spec$home,'imvigor011_sim_setup1.Rdata', sep ='/'), version=2) 

```
 

```{r sim, eval=F}
load('~/projects/stratification/imvigor011_sim_setup1.Rdata') 

# this chuck is supposed to be run separately

# run this first: #  ml load R

prep_cmd <- function(i, s = spec){
  
  log_home <- paste(spec$home, 'log', spec$run_name, sep = '/')
  if(!file.exists(log_home))   dir.create(log_home, recursive =T)
  
  log_out <-  paste(log_home, '/', i,'.cmd', sep='')
  cat("#!/bin/bash
    #SBATCH -J strat_sim
    #SBATCH --qos=short
    #SBATCH --cpus-per-task 4
    #SBATCH --mem-per-cpu=4G
    #SBATCH -o sim.o%J        
    #SBATCH -e sim.e%J
    ml R/R_4.1.0_Bioc_3.13/R-4.1.0-Bioc-3.13-prd-20210913
   
R CMD BATCH --no-save --no-restore '--args ", i+s$seed.base, " ", s$n, " ", s$dup, ' ', s$hr,' ', s$med,' ', s$nEvent,' ',s$run_name, " 2/3' ",  s$home, "/", s$run_code,' ', log_home,"/run_",i,".log "
    ,
      file =log_out, sep='')
  
  return(log_out)
  
}

# with strata

spec <- list(home  = '~/projects/stratification', run_name =  'ivg011_sim1',
             seed.base= 27518, 
             n = paste(cm2$n, collapse=','),  dup = '20', 
             hr = paste(rep(0.65, nrow(cm2) ), collapse=','), 
             med = paste(round(cm2$med,2), collapse=','), nEvent= '192', run_code = 'strat1b.r' , total_run=1000)

system(paste('cd', paste(spec$home,'log', sep ='/')))

#for (j in seq(1, spec$total_run , by= spec$n_run)) {
for (j in seq(1, spec$total_run , by= 1)) {
  system(paste('sbatch', prep_cmd(j, spec)))
}

# remove strata

spec$med <- paste(rep(4.4, nrow(cm2)), collapse=','); spec$run_name=  'ivg011_sim0';
 for (j in seq(1, spec$total_run , by= 1)) {
  system(paste('sbatch', prep_cmd(j, spec)))
}

```

# simulate imvigor011 power 


## sim without strata

```{r, warning=FALSE }

r0 <- readFolder.rdata( paste(spec$home,'reports/ivg011_sim0'  , sep = '/'), objName = 'r1')

knitr::kable( summarizeMatrix(r0[, c('n','nevent', 'p_s','delta_p')]), digits=3, caption =paste(' power of stratified:', round(mean( r0[, 'p_s'] <0.05) * 100, 1),'unstratified:', round(mean( r0[, 'p'] <0.05) * 100, 1)) )

```


## sim with with strata

 
```{r, warning=FALSE }

r1 <- readFolder.rdata( paste(spec$home,'reports/ivg011_sim1'  , sep = '/'), objName = 'r1')

knitr::kable( summarizeMatrix(r1[, c('n','nevent', 'p_s','delta_p')]), digits=3, caption =paste(' power of stratified:', round(mean( r1[, 'p_s'] <0.05) * 100, 1),'unstratified:', round(mean( r1[, 'p'] <0.05) * 100, 1)) )

```

# try different collapsing strategy

```{r sim_collpase, eval=F}
load('~/projects/stratification/imvigor011_sim_setup1.Rdata') 
M <- 1000  
prep_cmd2 <- function(i, s = spec){
  
  log_home <- paste(spec$home, 'log', spec$run_name, sep = '/')
  if(!file.exists(log_home))   dir.create(log_home, recursive =T)
  
  log_out <-  paste(log_home, '/', i,'.cmd', sep='')
  cat("#!/bin/bash
    #SBATCH -J strat_sim
    #SBATCH --qos=short
    #SBATCH --cpus-per-task 4
    #SBATCH --mem-per-cpu=4G
    #SBATCH -o sim.o%J        
    #SBATCH -e sim.e%J
    ml R/R_4.1.0_Bioc_3.13/R-4.1.0-Bioc-3.13-prd-20210913
   
R CMD BATCH --no-save --no-restore '--args ", i+s$seed.base,   " ", s$dup, ' ',  s$nEvent,' ',s$run_name, ' ', s$minE, " 2/3' ",  s$home, "/", s$run_code,' ', log_home,"/run_",i,".log "
    ,
      file =log_out, sep='')
  
  return(log_out)
  
}


spec <- list(home  = '~/projects/stratification', run_name =  'ivg011_sim2',
             seed.base= 27518, 
               dup = '20' , nEvent= '192', minE=10, run_code = 'strat3b.r' , total_run=M)

system(paste('cd', paste(spec$home,'log', sep ='/')))

#for (j in seq(1, spec$total_run , by= spec$n_run)) {
for (j in seq(1, spec$total_run , by= 1)) {
  system(paste('sbatch', prep_cmd2(j)))
}


# try different values of minE

spec <- list(home  = '~/projects/stratification', run_name =  'ivg011_sim3',
             seed.base= 27518, 
               dup = '20' , nEvent= '192', minE='6,20,2', run_code = 'strat3c.r' , total_run=M )

system(paste('cd', paste(spec$home,'log', sep ='/')))

#for (j in seq(1, spec$total_run , by= spec$n_run)) {
for (j in seq(1, spec$total_run , by= 1)) {
  system(paste('sbatch', prep_cmd2(j)))
}

 

```


## requiring 10 events per stratum

```{r, warning=FALSE }

 r1 <- readFolder.rdata( paste(spec$home,'reports/ivg011_sim2'  , sep = '/'), objName = 'r1')
 r2 <- readFolder.rdata( paste(spec$home,'reports/ivg011_sim2'  , sep = '/'), objName = 'r2')
knitr::kable( summarizeMatrix(r1[, c('n','nevent', 'p_s', 'p_cE','n_strata_cE','minStrataSize_cE', 'p_cN','n_strata_cN','minStrataSize_cN','delta_pE','delta_pN')]), digits=3, caption = paste( 'collapse groups based on event/patient number: power of stratified:', round(mean( r1[, 'p_cE'] <0.05) * 100, 1), '/', round(mean( r1[, 'p_cN'] <0.05) * 100, 1),'; unstratified:', round(mean( r1[, 'p'] <0.05) * 100, 1))  )
knitr::kable( summarizeMatrix(r2[, c('n','nevent', 'p_s', 'p_cE','n_strata_cE','minStrataSize_cE', 'p_cN','n_strata_cN','minStrataSize_cN','delta_pE','delta_pN')]), digits=3, caption = paste( 'remove small strata based on event/patient number: power of stratified:', round(mean( r2[, 'p_cE'] <0.05) * 100, 1),'/', round(mean( r2[, 'p_cN'] <0.05) * 100, 1), '; unstratified:', round(mean( r2[, 'p'] <0.05) * 100, 1))  )
 
```


## different number of minE

```{r, warning=FALSE }

 r1 <- readFolder.rdata( paste(spec$home,'reports/ivg011_sim3'  , sep = '/'), objName = 'r1')


p_ce <- with(r1, tapply(p_cE, minE, function(x)   mean( x <0.05)))
p_cn <- with(r1, tapply(p_cN, minE, function(x)   mean( x <0.05)))

plot(x = as.integer(names(p_ce)), y = p_ce, type='b', main = 'power changes as threshold number', ylab='power', xlab='minimal number of event/patient ')
lines(x = as.integer(names(p_cn)), y = p_cn, type='b', col='red')
legend('topright', lty=1, legend = c('# of events','# of Pts'), col=c('black','red'))

```
 
